# Generated by Django 3.2.12 on 2024-02-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Signin',
        ),
    ]
